djangowedding/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/login/$', views.login, name='login'),
    url(r'^user/logout/$', views.logout, name='logout'),
    url(r'^user/', include('user.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^gift/', include('gifts.urls')),
    url(r'^media/', include('mediafiles.urls')),
    url(r'', include('web.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes': settings.DEBUG}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT, 'show_indexes': settings.DEBUG}),
]

gifts/urls.py
from django.conf.urls import url
from . import views

app_name = 'gifts'

urlpatterns = [
    url(r'^$', views.GiftIndexView.as_view(),
        name='list'),

    url(r'^preamble/add/$', views.PreambleCreate.as_view(),
        name='preamble-create'),
    url(r'^preamble/(?P<pk>[0-9]+)/$', views.PreambleUpdate.as_view(),
        name='preamble-update'),
    url(r'^preamble/(?P<pk>[0-9]+)/delete/$', views.PreambleDelete.as_view(),
        name='preamble-delete'),

    url(r'^add/$', views.GiftCreate.as_view(),
        name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.GiftUpdate.as_view(),
        name='update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.GiftDelete.as_view(),
        name='delete'),
    url(r'^[0-9]+/reserve/$', views.GiftReserveView.as_view(),
        name='reserve'),
]

web/urls.py
from django.conf.urls import url

from . import views

app_name = 'web'

urlpatterns = [
    url(r'^$', views.main_page, name='index'),
    url(r'^questions/answer/$', views.question_answer, name='question_answer'),

    # News
    url(r'^news/add/$', views.NewsCreate.as_view(),
        name='news-create'),
    url(r'^news/$', views.NewsIndexView.as_view(),
        name='news-list'),
    url(r'^news/(?P<pk>[0-9]+)/$', views.NewsUpdate.as_view(),
        name='news-update'),
    url(r'^news/(?P<pk>[0-9]+)/delete/$', views.NewsDelete.as_view(),
        name='news-delete'),
    url(r'^news/feed/$', views.NewsFeed(),
        name='news-feed'),

    # Questions
    url(r'^question/add/$', views.QuestionCreate.as_view(),
        name='question-create'),
    url(r'^question/$', views.QuestionIndexView.as_view(),
        name='question-list'),
    url(r'^question/(?P<pk>[0-9]+)/$', views.QuestionUpdate.as_view(),
        name='question-update'),
    url(r'^question/(?P<pk>[0-9]+)/delete/$', views.QuestionDelete.as_view(),
        name='question-delete'),

    url(r'^question/(?P<pk>[0-9]+)/add-answer/$', views.AnswerView.as_view(),
        name='answer-create'),
    url(r'^answer/(?P<pk>[0-9]+)/$', views.AnswerUpdate.as_view(),
        name='answer-update'),
    url(r'^answer/(?P<pk>[0-9]+)/delete/$', views.AnswerDelete.as_view(),
        name='answer-delete'),

    # Registration
    url(r'^registration/add/$', views.RegistrationCreate.as_view(),
        name='registration-create'),
    url(r'^registration/thanks/$', views.RegistrationThanksView.as_view(),
        name='registration-thanks'),
    url(r'^registration/$', views.RegistrationIndexView.as_view(),
        name='registration-list'),
    url(r'^registration/(?P<pk>[0-9]+)/$', views.RegistrationUpdate.as_view(),
        name='registration-update'),
    url(r'^registration/(?P<pk>[0-9]+)/delete/$', views.RegistrationDelete.as_view(),
        name='registration-delete'),

    # Announce mail
    url(r'^mail/add/$', views.AnnounceMailCreate.as_view(),
        name='announce-mail-create'),
    url(r'^mail/ok/$', views.AnnounceMailOkView.as_view(),
        name='announce-mail-ok'),
]

gifts/models.py
import markdown

from django.db import models
from django.utils.translation import ugettext_lazy as _

class Gift(models.Model):
    title = models.CharField(max_length=200, verbose_name=_("Title"))
    description = models.TextField(verbose_name=_("Description"))
    capacity = models.IntegerField(default=1, verbose_name=_("Capacity"))
    reserved = models.IntegerField(default=0)
    image = models.FileField()

    def __str__(self):
        return self.title

    def get_html_description(self):
        return markdown.markdown(self.description)

    @property
    def free_count(self):
        if self.capacity == -1:
            return "infinite"
        return self.capacity - self.reserved

    @property
    def enabled(self):
        if self.capacity == -1:
            return True
        return self.capacity > self.reserved


class Preamble(models.Model):
    text = models.TextField(verbose_name=_("Text"))

    def __str__(self):
        return self.text[:10]

    def get_html_list(self):
        md_list = self.text.split('\r\n~~~\r\n')
        return [markdown.markdown(md) for md in md_list]

    def get_html_first(self):
        md_list = self.text.split('\r\n~~~\r\n')
        return markdown.markdown(md_list[0])

    def get_html_tail(self):
        md_list = self.text.split('\r\n~~~\r\n')
        return [markdown.markdown(md) for md in md_list[1:]]

gifts/views.py
import re

from django.core.mail import EmailMultiAlternatives
from django.shortcuts import render
from django.template.loader import get_template
from django.views.generic import CreateView, UpdateView, DeleteView, TemplateView, ListView
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User

from .models import Gift, Preamble

class GiftIndexView(ListView):
    model = Gift
    context_object_name = 'all_gifts'
    ordering = 'title'
    message = None

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['message'] = self.message
        ctx['title'] = "(Milo)dary"
        ctx['preambles'] = Preamble.objects.order_by('id')
        return ctx

    def get_queryset(self):
        set = super().get_queryset()
        return set




class GiftCreate(CreateView):
    model = Gift
    fields = ['title', 'description', 'capacity', 'image']

    def get_success_url(self):
        return reverse_lazy('gifts:list') + "#content"


class GiftUpdate(UpdateView):
    model = Gift
    fields = ['title', 'description', 'capacity', 'reserved', 'image']

    def get_success_url(self):
        return reverse_lazy('gifts:list') + "#content"


class GiftDelete(DeleteView):
    model = Gift

    def get_success_url(self):
        return reverse_lazy('gifts:list') + "#content"


class GiftReserveView(TemplateView):
    def get(self, request, *args, **kwargs):
        gift_match = re.match(r'/gift/([0-9]+)/reserve/?', request.path)
        if gift_match:
            try:
                gift = Gift.objects.get(pk=gift_match.group(1))
            except:
                giw = GiftIndexView()
                giw.request = request
                giw.message = _("Gift not found")
                return giw.get(request)
        return render(request, 'gifts/gift_confirm.html', {'confirm_title': 'Potvrdit rezervaci daru',
                                                    'confirm_text': "Zarezervovat",
                                                    "object": gift})

    def post(self, request):
        message = "Dar se nepodařilo zarezervovat!"
        try:
            gift_match = re.match(r'/gift/([0-9]+)/reserve/?', request.path)
            if gift_match:
                gift = Gift.objects.get(pk=gift_match.group(1))

                if gift.free_count == "infinite" or gift.free_count > 0:
                    gift.reserved += 1
                    gift.save()
                    message = _("Gift reserved!")

                    for user in User.objects.all():
                        if user.groups.filter(name='notification').exists():

                            plaintext = get_template('gifts/email.txt')
                            html = get_template('gifts/email.html')
                            d = {'gift': gift}
                            text_content = plaintext.render(d)
                            html_content = html.render(d)

                            msg = EmailMultiAlternatives(subject=_("Gifts"),
                                                         from_email="svatba@frantisekadominika.tk",
                                                         reply_to=["lachmanfrantisek@gmail.com"],
                                                         to=[user.email],
                                                         body=text_content)

                            msg.attach_alternative(html_content, "text/html")
                            msg.send(fail_silently=True)

                else:
                    message = _("Gift cannot be reserved!")
        except Exception as ex:
            print(ex)

        giw = GiftIndexView()
        giw.request = request
        giw.message = message
        return giw.get(request)

class PreambleCreate(CreateView):
    model = Preamble
    fields = ['text']

    def get_success_url(self):
        return reverse_lazy('gifts:list') + "#content"


class PreambleUpdate(UpdateView):
    model = Preamble
    fields = ['id', 'text']

    def get_success_url(self):
        return reverse_lazy('gifts:list') + "#content"


class PreambleDelete(DeleteView):
    model = Preamble

    def get_success_url(self):
        return reverse_lazy('gifts:list') + "#content"

gifts/templates/gifts/email.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en" style="box-sizing: border-box;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;overflow-x: hidden;font-family: Verdana,sans-serif;font-size: 15px;line-height: 1.5;">
<head style="box-sizing: inherit;">
    <meta charset="UTF-8" style="box-sizing: inherit;">
    <title style="box-sizing: inherit;">{% trans "Gifts" %}</title>
</head>
<body style="box-sizing: inherit;margin: 0;font-size: 15px;font-family: Verdana,sans-serif;line-height: 1.5;">
<div style="box-sizing: inherit;font-family: 'Lobster';box-shadow: 0 4px 10px 0 rgba(0,0,0,0.2),0 4px 20px 0 rgba(0,0,0,0.19);transition: 0.5s;opacity: 0.8;margin: 16px!important;padding: 8px 16px!important;background-color: rgb(139, 150, 32)!important;color: rgb(239, 229, 217)!important;">
<h3 style="box-sizing: inherit;font-size: 24px;font-family: 'Lobster';font-weight: 400;margin: 10px 0;">{% trans "Gifts" %}</h3>
</div>

<div style="box-sizing: inherit;font-family: 'Lobster';box-shadow: 0 4px 10px 0 rgba(0,0,0,0.2),0 4px 20px 0 rgba(0,0,0,0.19);transition: 0.5s;opacity: 0.7;border-left: 6px solid #ccc!important;margin: 16px!important;padding: 8px 16px!important;background-color: rgb(239, 229, 217)!important;color: black!important;border-color: rgb(139, 150, 32)!important;">
    <p style="box-sizing: inherit;">
        {% blocktrans %}There is a new reservation of the{% endblocktrans %} <strong style="box-sizing: inherit;">{{ gift.title }}</strong> ({{ gift.reserved }} / {{ gift.capacity }}).
    </p>
    <br/>
    <br/>
    <p style="box-sizing: inherit; font-style: italic;">
    {% trans "Your wedding page." %}
    </p>
</div>



</body>
</html>

gifts/templates/gifts/gift_confirm.html
{% extends 'web/base.html' %}
{% load i18n %}

{% block content %}
<div class="w3-margin w3-padding w3-card-4 w-green w-text-gray w-opacity">
    <h2>{% trans "Confirm gift reservation" %}</h2>
</div>

<form method="POST" class="w3-card-4 w3-margin w3-padding w3-leftbar w-form w-opacity w-gray w-text-green w-border-green" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="w-text-black">
      <h2>{{ object.title }}</h2>
      {{ object.get_html_description|safe }}
    </div>
    <button type="submit" class="w-button w-hover-opacity w-text-green w-border-green w-gray">{% trans "Confirm the reservation of one piece" %}</button>

</form>

{% endblock %}

gifts/templates/gifts/gift_confirm_delete.html
{% extends 'web/base.html' %}
{% load i18n %}

{% block content %}
<div class="w3-margin w3-padding w3-card-4 w-green w-text-gray w-opacity">
    <h2>{% trans "Delete gift" %}</h2>
</div>
{% if user.is_authenticated %}
<form method="POST" class="w3-card-4 w3-margin w3-padding w3-leftbar w-form w-opacity w-gray w-text-green w-border-green" enctype="multipart/form-data">
    <div class="w-text-black">
      <h2>{{ object.title }}</h2>
      {{ object.get_html_description|safe }}
    </div>
    {% csrf_token %}
    <button type="submit" class="w-button w-hover-opacity w-text-green w-border-green w-gray">{% trans "Delete" %}</button>
</form>
{% else %}
<div class="w3-card-4 w3-margin w3-padding w3-leftbar w-opacity w-gray w-text-black w-border-green w-opacity">
{% trans "You are not allowed to delete gifts." %}
</div>
{% endif %}
{% endblock %}

gifts/templates/gifts/gift_form.html
{% extends 'web/base.html' %}
{% load i18n %}

{% block content %}
<div class="w3-margin w3-padding w3-card-4 w-green w-text-gray w-opacity">
    <h2>{% trans "Gift" %}</h2>
</div>
{% if user.is_authenticated %}
<form method="POST" class="w3-card-4 w3-margin w3-padding w3-leftbar w-form w-opacity w-gray w-text-green w-border-green" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
            <label class="">{{field.label_tag}}</label>
            <div class="">{{ field }}</div>
            <div class="">{{ field.errors }}</div>
    {% endfor %}

    <button type="submit" class="w-button w-hover-opacity w-text-green w-border-green w-gray">{% trans "Save" %}</button>

</form>

{% else %}
<div class="w3-card-4 w3-margin w3-padding w3-leftbar w-opacity w-gray w-text-black w-border-green w-opacity">
{% trans "You are not allowed to edit gifts." %}
</div>
{% endif %}

{% endblock %}

gifts/templates/gifts/gift_list.html
{% extends 'web/base.html' %}
{% load i18n %}

{% block content %}

<div class="w3-card-4 w3-padding w3-margin w-opacity w-green w-text-gray">
    <h2>{% trans "Gifts/Wishes" %}
        {% if user.is_authenticated %}
        <span class="delimiter">&#124;</span>
        <a href="{% url 'gifts:create' %}">
            <div class="w-button w-hover-opacity w-text-gray w-border-gray">{% trans "Add" %}</div>
        </a>

        <a href="{% url 'gifts:preamble-create' %}">
            <div class="w-button w-hover-opacity w-text-gray w-border-gray">{% trans "Add preamble" %}</div>
        </a>
        {% endif %}
    </h2>
</div>

{% for p in preambles %}
  <div class="w3-card-4 w3-leftbar w3-padding w3-margin w3-center w-gray w-text-black w-border-green w-opacity">
    {% if user.is_authenticated %}
    <div class="w3-right-align w3-large">
        <a href="{% url 'gifts:list' %}preamble/{{ p.id }}/"><i
                class="fa fa-bars w-hover-opacity w-text-green"></i></a>

        <span class="delimiter">&#124;</span>
        <a href="{% url 'gifts:list' %}preamble/{{ p.id }}/delete/"><i
                class="fa fa-close w-hover-opacity w-text-green"></i></a>
    </div>
    {% endif %}
    {{ p.get_html_first|safe }}
  </div>

  {% for p_html in p.get_html_tail %}
  <div class="w3-card-4 w3-leftbar w3-padding w3-margin w3-center w-gray w-text-black w-border-green w-opacity">
      {{ p_html|safe }}
  </div>
  {% endfor %}
{% endfor %}

{%if message %}
<div id="content" class="w3-card-4 w3-leftbar w3-padding w3-margin w3-center w-gray w-text-black w-border-green w-opacity">
<h3>{{ message }}</h3>
</div>
{% endif %}

<div>
{% for g in all_gifts %}
<div class="w3-card-4 w-card w3-margin w3-leftbar w3-padding w-text-black w-gray w-border-green w-opacity {% if not g.enabled %} w-disabled{% endif %}">
    {% if user.is_authenticated %}
    <div class="w3-right-align w3-large">
        <span class="w-text-green">{{ g.reserved }} / {{ g.capacity }}</span>
        <span class="delimiter">&#124;</span>
        <a href="{% url 'gifts:list' %}{{ g.id }}/#content"><i
                class="fa fa-bars w-hover-opacity w-text-green"></i></a>

        <span class="delimiter">&#124;</span>
        <a href="{% url 'gifts:list' %}{{ g.id }}/delete/#content"><i
                class="fa fa-close w-hover-opacity w-text-green"></i></a>
    </div>
    {% endif %}
    <h2>{{ g.title }} </h2>
    <img src="{{ g.image.url }}" class="w-card-img"/>
    <p>{{ g.get_html_description|safe }}</p>
    <a href="{% url 'gifts:list' %}{{ g.id }}/reserve/#content">
        {% if g.enabled %}
        <div class="w-button w-hover-opacity w-text-green w-border-green">{% trans "Reserve" %}</div>
        {% endif %}
    </a>
    {% if g.free_count == "infinite" %}
    <div class="w3-right-align">{% trans "infinite" %}</div>
    {% elif g.free_count > 1 %}
    <div class="w3-right-align">{% trans "count" %}: {{ g.free_count }}</div>
    {% endif %}
</div>
{% endfor %}

</div>

{% endblock content %}

gifts/templates/gifts/preamble_confirm_delete.html
{% extends 'web/base.html' %}
{% load i18n %}

{% block content %}
<div class="w3-margin w3-padding w3-card-4 w-green w-text-gray w-opacity">
    <h2>{% trans "Delete preamble" %}</h2>
</div>
{% if user.is_authenticated %}
<form method="POST" class="w3-card-4 w3-margin w3-padding w3-leftbar w-form w-opacity w-gray w-text-green w-border-green" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <label class="form label">{{field.label_tag}}</label>
    <div class="form text-area">{{ field }}</div>
    <div class="">{{ field.errors }}</div>
    {% endfor %}

    <button type="submit" class="w-button w-hover-opacity w-text-green w-border-green w-gray">{% trans "Confirm" %}</button>
</form>
{% else %}
<div class="w3-card-4 w3-margin w3-padding w3-leftbar w-opacity w-gray w-text-black w-border-green w-opacity">
{% trans "You are not allowed to delete preambles." %}
</div>
{% endif %}
{% endblock %}

gifts/templates/gifts/preamble_form.html
{% extends 'web/base.html' %}
{% load i18n %}

{% block content %}
<div class="w3-margin w3-padding w3-card-4 w-green w-text-gray w-opacity">
    <h2>{% trans "Preamble" %}</h2>
</div>
{% if user.is_authenticated %}
<form method="POST" class="w3-card-4 w3-margin w3-padding w3-leftbar w-form w-opacity w-gray w-text-green w-border-green" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
            <label class="">{{field.label_tag}}</label>
            <div class="">{{ field }}</div>
            <div class="">{{ field.errors }}</div>
    {% endfor %}

    <button type="submit" class="w-button w-hover-opacity w-text-green w-border-green w-gray">{% trans "Save" %}</button>

</form>

{% else %}
<div class="w3-card-4 w3-margin w3-padding w3-leftbar w-opacity w-gray w-text-black w-border-green w-opacity">
{% trans "You are not allowed to edit preambles." %}
</div>
{% endif %}

{% endblock %}