articles/urls.py
from django.conf.urls import url

from articles import views

app_name = 'articles'

urlpatterns = [
    url(r'^$', views.ArticleIndexView.as_view(),
        name='list'),
    url(r'^id/(?P<pk>[0-9]+)/$', views.ArticleUpdate.as_view(),
        name='article-update'),
    url(r'^id/(?P<pk>[0-9]+)/delete/$', views.ArticleDelete.as_view(),
        name='article-delete'),
    url(r'^add/$', views.ArticleCreate.as_view(), name='create'),
    url(r'^', views.articles, name='articles'),
]

djangowedding/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/login/$', views.login, name='login'),
    url(r'^user/logout/$', views.logout, name='logout'),
    url(r'^user/', include('user.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^gift/', include('gifts.urls')),
    url(r'^media/', include('mediafiles.urls')),
    url(r'', include('web.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes': settings.DEBUG}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT, 'show_indexes': settings.DEBUG}),
]

web/urls.py
from django.conf.urls import url

from . import views

app_name = 'web'

urlpatterns = [
    url(r'^$', views.main_page, name='index'),
    url(r'^questions/answer/$', views.question_answer, name='question_answer'),

    # News
    url(r'^news/add/$', views.NewsCreate.as_view(),
        name='news-create'),
    url(r'^news/$', views.NewsIndexView.as_view(),
        name='news-list'),
    url(r'^news/(?P<pk>[0-9]+)/$', views.NewsUpdate.as_view(),
        name='news-update'),
    url(r'^news/(?P<pk>[0-9]+)/delete/$', views.NewsDelete.as_view(),
        name='news-delete'),
    url(r'^news/feed/$', views.NewsFeed(),
        name='news-feed'),

    # Questions
    url(r'^question/add/$', views.QuestionCreate.as_view(),
        name='question-create'),
    url(r'^question/$', views.QuestionIndexView.as_view(),
        name='question-list'),
    url(r'^question/(?P<pk>[0-9]+)/$', views.QuestionUpdate.as_view(),
        name='question-update'),
    url(r'^question/(?P<pk>[0-9]+)/delete/$', views.QuestionDelete.as_view(),
        name='question-delete'),

    url(r'^question/(?P<pk>[0-9]+)/add-answer/$', views.AnswerView.as_view(),
        name='answer-create'),
    url(r'^answer/(?P<pk>[0-9]+)/$', views.AnswerUpdate.as_view(),
        name='answer-update'),
    url(r'^answer/(?P<pk>[0-9]+)/delete/$', views.AnswerDelete.as_view(),
        name='answer-delete'),

    # Registration
    url(r'^registration/add/$', views.RegistrationCreate.as_view(),
        name='registration-create'),
    url(r'^registration/thanks/$', views.RegistrationThanksView.as_view(),
        name='registration-thanks'),
    url(r'^registration/$', views.RegistrationIndexView.as_view(),
        name='registration-list'),
    url(r'^registration/(?P<pk>[0-9]+)/$', views.RegistrationUpdate.as_view(),
        name='registration-update'),
    url(r'^registration/(?P<pk>[0-9]+)/delete/$', views.RegistrationDelete.as_view(),
        name='registration-delete'),

    # Announce mail
    url(r'^mail/add/$', views.AnnounceMailCreate.as_view(),
        name='announce-mail-create'),
    url(r'^mail/ok/$', views.AnnounceMailOkView.as_view(),
        name='announce-mail-ok'),
]

articles/models.py
import markdown
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Article(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("Link-name"))
    title = models.CharField(max_length=200, verbose_name=_("Title"))
    text = models.TextField(verbose_name=_("Markdown-formatted text content"))

    def __str__(self):
        return self.title

    def get_html_list(self):
        md_list = self.text.split('\r\n~~~\r\n')
        return [markdown.markdown(md) for md in md_list]

articles/views.py
import re

from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import UpdateView, CreateView, DeleteView

from articles.models import Article


def articles(request):
    article_match = re.match(r'/articles/([^/?]*)/?', request.path)
    if article_match:
        article = Article.objects.filter(name=article_match.group(1))
        if len(article) == 1:
            return render(request, 'articles/article.html',
                          context={
                              'article': article[0],
                              'title': article[0].title,
                          })
    return render(request, 'articles/no_article.html', {})


class ArticleUpdate(UpdateView):
    model = Article
    fields = ['name', 'title', 'text']

    def get_success_url(self):
        return "/articles/{}/".format(self.get_object().name)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["title"] = "Upravit článek: "
        return ctx


class ArticleCreate(CreateView):
    model = Article
    fields = ['name', 'title', 'text']
    success_url = reverse_lazy('articles:list')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["title"] = "Vytvořit článek"
        return ctx


class ArticleDelete(DeleteView):
    model = Article
    success_url = reverse_lazy('articles:list')

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["title"] = "Smazat článek: "
        return ctx

class ArticleIndexView(generic.ListView):
    model = Article
    ordering = '-title'

articles/templates/articles/article.html
{% extends 'web/base.html' %}
{% load i18n %}

{% block content %}

<div class="w3-margin w3-padding w3-card-4 w-green w-text-gray w-opacity">
    {% if user.is_authenticated %}
    <div class="w3-right-align w3-large">
        <a href="/articles/id/{{ article.id }}/"><i
                class="fa fa-bars w-hover-opacity w-text-gray"></i></a>

        <span class="delimiter">&#124;</span>
        <a href="/articles/id/{{ article.id }}/delete/"><i
                class="fa fa-close w-hover-opacity gray"></i></a>
    </div>
    {% endif %}
    <h2>{{ article.title }}</h2>
</div>

{% for p in article.get_html_list %}
<div class="w3-card-4 w3-leftbar w3-padding w3-margin w3-center w-gray w-text-black w-border-green w-opacity">
    {{ p|safe }}
</div>
{% endfor %}


{% endblock content %}

articles/templates/articles/article_confirm_delete.html
{% extends 'web/base.html' %}
{% load i18n %}

{% block content %}
<div class="w3-margin w3-padding w3-card-4 w-green w-text-gray w-opacity">
    <h2>{% trans "Delete article" %}</h2>
</div>
{% if user.is_authenticated %}
<form method="POST" class="w3-card-4 w3-margin w3-padding w3-leftbar w-form w-opacity w-gray w-text-green w-border-green" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <label class="form label">{{field.label_tag}}</label>
    <div class="form text-area">{{ field }}</div>
    <div class="">{{ field.errors }}</div>
    {% endfor %}

    <button type="submit" class="w-button w-hover-opacity w-text-green w-border-green w-gray">{% trans "Confirm" %}</button>

</form>

{% else %}
<div class="w3-card-4 w3-margin w3-padding w3-leftbar w-opacity w-gray w-text-black w-border-green w-opacity">
{% trans "You are not allowed to delete articles." %}
</div>
{% endif %}

{% endblock %}

articles/templates/articles/article_form.html
{% extends 'web/base.html' %}
{% load i18n %}

{% block content %}
<div class="w3-margin w3-padding w3-card-4 w-green w-text-gray w-opacity">
    <h2>{{ title }}{{ article.title }}</h2>
</div>
{% if user.is_authenticated %}
<form method="POST" class="w3-card-4 w3-margin w3-padding w3-leftbar w-form w-opacity w-gray w-text-green w-border-green" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
            <label class="">{{field.label_tag}}</label>
            <div class="">{{ field }}</div>
            <div class="">{{ field.errors }}</div>
    {% endfor %}


    <button type="submit" class="w-button w-hover-opacity w-text-green w-border-green w-gray">{% trans "Save" %}</button>

</form>

{% else %}
<div class="w3-card-4 w3-margin w3-padding w3-leftbar w-opacity w-gray w-text-black w-border-green w-opacity">
{% trans "You are not allowed to edit articles." %}
</div>
{% endif %}

{% endblock %}

articles/templates/articles/article_list.html
{% extends 'web/base.html' %}
{% load i18n %}

{% block content %}

<div class="w3-container w3-margin w-opacity w-green w-text-gray">

    <h2>{% trans "Articles" %}&nbsp;&nbsp;
        {% if user.is_authenticated %}
        <span class="delimiter">&#124;</span>
        <a href="{% url 'articles:create' %}">
            <span class="w-button w-hover-opacity w-text-gray w-border-gray">{% trans "Add new" %}</span>
        </a>
        &nbsp;&nbsp;
        {% endif %}
    </h2>
</div>

{% for article in article_list %}
<div class="w3-card-4 w3-leftbar w3-padding w3-margin w3-center w-border-green w-gray w-opacity">
    {% if user.is_authenticated %}
    <div class="w3-right-align w3-large w3-cell-middle">

        <a href="{% url 'articles:list' %}{{ article.name }}/">
            <span class="w3-medium w-button w-hover-opacity w-text-green w-border-green w-gray">
                <i class="fa fa-link w-hover-opacity w-text-green"></i> &nbsp;{{ article.name }}
            </span>
        </a>

        <span class="delimiter">&#124;</span>

        <a href="{% url 'articles:list' %}id/{{ article.id }}/"><i
                class="fa fa-bars w-hover-opacity w-text-green"></i></a>

        <span class="delimiter">&#124;</span>

        <a href="{% url 'articles:list' %}id/{{ article.id }}/delete/"><i
                class="fa fa-close w-hover-opacity w-text-green"></i></a>

    </div>
    {% endif %}
    {{ article.title }}

</div>
{% endfor %}

{% endblock content %}

articles/templates/articles/no_article.html
{% extends 'web/base.html' %}
{% load i18n %}
{% trans "Articles" %}

{% block content %}

<div class="w3-margin w3-padding w3-card-4 w-green w-text-gray w-opacity">
<h2>{% trans "Article not found!" %}</h2>
</div>

{% endblock content %}