djangowedding/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/login/$', views.login, name='login'),
    url(r'^user/logout/$', views.logout, name='logout'),
    url(r'^user/', include('user.urls')),
    url(r'^articles/', include('articles.urls')),
    url(r'^gift/', include('gifts.urls')),
    url(r'^media/', include('mediafiles.urls')),
    url(r'', include('web.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes': settings.DEBUG}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT, 'show_indexes': settings.DEBUG}),
]

web/urls.py
from django.conf.urls import url

from . import views

app_name = 'web'

urlpatterns = [
    url(r'^$', views.main_page, name='index'),
    url(r'^questions/answer/$', views.question_answer, name='question_answer'),

    # News
    url(r'^news/add/$', views.NewsCreate.as_view(),
        name='news-create'),
    url(r'^news/$', views.NewsIndexView.as_view(),
        name='news-list'),
    url(r'^news/(?P<pk>[0-9]+)/$', views.NewsUpdate.as_view(),
        name='news-update'),
    url(r'^news/(?P<pk>[0-9]+)/delete/$', views.NewsDelete.as_view(),
        name='news-delete'),
    url(r'^news/feed/$', views.NewsFeed(),
        name='news-feed'),

    # Questions
    url(r'^question/add/$', views.QuestionCreate.as_view(),
        name='question-create'),
    url(r'^question/$', views.QuestionIndexView.as_view(),
        name='question-list'),
    url(r'^question/(?P<pk>[0-9]+)/$', views.QuestionUpdate.as_view(),
        name='question-update'),
    url(r'^question/(?P<pk>[0-9]+)/delete/$', views.QuestionDelete.as_view(),
        name='question-delete'),

    url(r'^question/(?P<pk>[0-9]+)/add-answer/$', views.AnswerView.as_view(),
        name='answer-create'),
    url(r'^answer/(?P<pk>[0-9]+)/$', views.AnswerUpdate.as_view(),
        name='answer-update'),
    url(r'^answer/(?P<pk>[0-9]+)/delete/$', views.AnswerDelete.as_view(),
        name='answer-delete'),

    # Registration
    url(r'^registration/add/$', views.RegistrationCreate.as_view(),
        name='registration-create'),
    url(r'^registration/thanks/$', views.RegistrationThanksView.as_view(),
        name='registration-thanks'),
    url(r'^registration/$', views.RegistrationIndexView.as_view(),
        name='registration-list'),
    url(r'^registration/(?P<pk>[0-9]+)/$', views.RegistrationUpdate.as_view(),
        name='registration-update'),
    url(r'^registration/(?P<pk>[0-9]+)/delete/$', views.RegistrationDelete.as_view(),
        name='registration-delete'),

    # Announce mail
    url(r'^mail/add/$', views.AnnounceMailCreate.as_view(),
        name='announce-mail-create'),
    url(r'^mail/ok/$', views.AnnounceMailOkView.as_view(),
        name='announce-mail-ok'),
]

web/templates/web/announce-mail-ok.html
{% extends 'web/base.html' %}
{% load i18n %}

{% block content %}

<div class="w3-card-4 w3-padding w3-margin w-opacity w-green w-text-gray">
    <h2>{% trans "Mail send" %}</h2>
</div>

{% endblock content %}

web/templates/web/announce-mail.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en" style="box-sizing: border-box;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;overflow-x: hidden;font-family: Verdana,sans-serif;font-size: 15px;line-height: 1.5;">
<head style="box-sizing: inherit;">
    <meta charset="UTF-8" style="box-sizing: inherit;">
    <title style="box-sizing: inherit;">{% trans "Registration" %}</title>
</head>
<body style="box-sizing: inherit;margin: 0;font-size: 15px;font-family: Verdana,sans-serif;line-height: 1.5;">
<div style="box-sizing: inherit;font-family: 'Lobster';box-shadow: 0 4px 10px 0 rgba(0,0,0,0.2),0 4px 20px 0 rgba(0,0,0,0.19);transition: 0.5s;opacity: 0.8;margin: 16px!important;padding: 8px 16px!important;background-color: rgb(139, 150, 32)!important;color: rgb(239, 229, 217)!important;">
<h3 style="box-sizing: inherit;font-size: 24px;font-family: 'Lobster';font-weight: 400;margin: 10px 0;">{{ subject }}</h3>
</div>

<div style="box-sizing: inherit;font-family: 'Lobster';box-shadow: 0 4px 10px 0 rgba(0,0,0,0.2),0 4px 20px 0 rgba(0,0,0,0.19);transition: 0.5s;opacity: 0.7;border-left: 6px solid #ccc!important;margin: 16px!important;padding: 8px 16px!important;background-color: rgb(239, 229, 217)!important;color: black!important;border-color: rgb(139, 150, 32)!important;">
    <h2>{% blocktrans %}Dear Weddings{% endblocktrans %}!</h2>
    <p style="box-sizing: inherit;">
        {{ content }}
    </p>

    <br/>
    <p style="box-sizing: inherit; font-style: italic;">
    {% trans "Your newlyweds" %}
    </p>
</div>

</body>
</html>

web/templates/web/announcemail_form.html
{% extends 'web/base.html' %}
{% load i18n %}

{% block content %}
    <div class="w3-card-4 w3-margin w3-padding w-opacity w-green w-text-gray">
        <h2>{% trans "New mail" %}</h2>
    </div>

    <form method="POST" class="w3-card-4 w3-margin w3-padding w3-leftbar w-form w-opacity w-gray w-text-green w-border-green">{% csrf_token %}
        {% for field in form %}
            <label class="">{{field.label_tag}}</label>
            <div class="">{{ field }}</div>
            <div class="">{{ field.errors }}</div>
        {% endfor %}

        <button type="submit" class="w-button w-hover-opacity w-text-green w-border-green w-gray">{% trans "Send" %}</button>
    </form>
{% endblock %}

web/templates/web/answer_confirm_delete.html
{% extends 'web/base.html' %}
{% load i18n %}

{% block content %}
<div class="w3-margin w3-padding w3-card-4 w-green w-text-gray w-opacity">
    <h2>{% trans "Delete answer" %}</h2>
</div>
{% if user.is_authenticated %}
<form method="POST" class="w3-card-4 w3-margin w3-padding w3-leftbar w-form w-opacity w-gray w-text-green w-border-green" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
            <label class="">{{field.label_tag}}</label>
            <div class="">{{ field }}</div>
            <div class="">{{ field.errors }}</div>
    {% endfor %}


    <button type="submit" class="w-button w-hover-opacity w-text-green w-border-green w-gray">{% trans "Confirm" %}</button>

</form>

{% else %}
<div class="w3-card-4 w3-margin w3-padding w3-leftbar w-opacity w-gray w-text-black w-border-green w-opacity">
{% trans "You are not allowed to delete the answer." %}
</div>
{% endif %}

{% endblock %}

web/templates/web/base.html
{% load menu_generator %}
{% load i18n %}

<html>
<head>
    <title>Svatba &#9829; {% if title %}{{ title }}{% endif %}</title>
    <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet"
          type="text/css">
    <link rel="stylesheet" href="/static/css/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/css/web.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<a href="/#content">
<div class="w3-card-4 w3-margin w3-padding w-green w-text-gray w3-center w-opacity">
    <h1>František a Dominika</h1>
</div>
</a>

<div class="w3-margin w3-center">
    {% get_menu "MAIN_MENU" as main_menu %}
    {% for item in main_menu %}
    <a href="{{ item.url }}#content">
        <span class="w3-large w3-card-4 w3-show-inline-block w-margin w-hover-movedown w3-padding w-opacity w-gray {% if item.selected %}w-text-green{% else %}w-text-black{% endif %}">{{ item.name }}</span>
    </a>
    {% endfor %}
    {% if not user.is_authenticated %}
    <a href="{% url 'login' %}?next={% firstof request.path '/' %}"><span
            class="w3-large w3-card-4 w3-show-inline-block w-margin w-hover-movedown w3-padding w-opacity w-gray {% if request.path == '/user/login/'%}w-text-green{% else %}w-text-black{% endif %}">Admin</span></a>
    {% endif %}
</div>
<div class="content-point" {% if not message %}id="content"{% endif %}></div>
<div class="content container">
    {% block content %}
    {% endblock %}
    <div class="w3-right-align"><a href="#top"><i
            class="w3-margin w3-card-4 w3-large w3-leftbar w-border-green w3-padding-16 w3-padding fa fa-arrow-up w-opacity w-hover-opacity w-text-green w-gray"></i></a>
    </div>
</div>
{% if request.path != "/accounts/login/"%}
<div class="user container">
    {% if user.is_authenticated %}
    <div class="w3-card-4 w3-margin w3-padding w-opacity w-green w-text-gray">
                <span class="text-in-item">
                    {% trans "Logged user:" %} <span class="user name">{{ user }}</span>
                </span>
        <span class="delimiter">&#124;</span>
        <a href="{% url 'logout' %}?next={% firstof request.path '/' %}#content">
            <div class="btnlogout">{% trans "Log out" %}</div>
        </a>
      {% if user.is_superuser %}
  	    {% get_current_language as LANG %}
  	    {% get_current_language as LANGUAGE_CODE %}
  	    {{ LANG }} | {{ LANGUAGE_CODE }}
      {% endif %}
    </div>
    {% endif %}
</div>
{% endif %}
</body>
</html>

web/templates/web/email.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en" style="box-sizing: border-box;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;overflow-x: hidden;font-family: Verdana,sans-serif;font-size: 15px;line-height: 1.5;">
<head style="box-sizing: inherit;">
    <meta charset="UTF-8" style="box-sizing: inherit;">
    <title style="box-sizing: inherit;">{% trans "Registration" %}</title>
</head>
<body style="box-sizing: inherit;margin: 0;font-size: 15px;font-family: Verdana,sans-serif;line-height: 1.5;">
<div style="box-sizing: inherit;font-family: 'Lobster';box-shadow: 0 4px 10px 0 rgba(0,0,0,0.2),0 4px 20px 0 rgba(0,0,0,0.19);transition: 0.5s;opacity: 0.8;margin: 16px!important;padding: 8px 16px!important;background-color: rgb(139, 150, 32)!important;color: rgb(239, 229, 217)!important;">
<h3 style="box-sizing: inherit;font-size: 24px;font-family: 'Lobster';font-weight: 400;margin: 10px 0;">{% trans "Registration" %}</h3>
</div>

<div style="box-sizing: inherit;font-family: 'Lobster';box-shadow: 0 4px 10px 0 rgba(0,0,0,0.2),0 4px 20px 0 rgba(0,0,0,0.19);transition: 0.5s;opacity: 0.7;border-left: 6px solid #ccc!important;margin: 16px!important;padding: 8px 16px!important;background-color: rgb(239, 229, 217)!important;color: black!important;border-color: rgb(139, 150, 32)!important;">
    {% blocktrans %}There is a new registration:{% endblocktrans %}

    <h2>{{ registration.name }} ({{ registration.people_count }})</h2>
    <p style="box-sizing: inherit;">
        {% if registration.go_to_lunch %} {% trans "Lunch" %} {% endif %}
      {% if registration.go_to_party %} {% trans "Party" %} {% endif %}
      -> {{ registration.mail }}
    </p>


    <br/>
    <br/>
    <p style="box-sizing: inherit; font-style: italic;">
    {% trans "Your wedding page." %}
    </p>
</div>

</body>
</html>

web/templates/web/question-email.html
{% load i18n %}
<!DOCTYPE html>
<html lang="cs"
      style="box-sizing: border-box;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;overflow-x: hidden;font-family: Verdana,sans-serif;font-size: 15px;line-height: 1.5;">
<head style="box-sizing: inherit;">
    <meta charset="UTF-8" style="box-sizing: inherit;">
    <title style="box-sizing: inherit;">{% trans "Question" %}</title>
</head>
<body style="box-sizing: inherit;margin: 0;font-size: 15px;font-family: Verdana,sans-serif;line-height: 1.5;">
<div style="box-sizing: inherit;font-family: 'Lobster';box-shadow: 0 4px 10px 0 rgba(0,0,0,0.2),0 4px 20px 0 rgba(0,0,0,0.19);transition: 0.5s;opacity: 0.8;margin: 16px!important;padding: 8px 16px!important;background-color: rgb(139, 150, 32)!important;color: rgb(239, 229, 217)!important;">
    <h3 style="box-sizing: inherit;font-size: 24px;font-family: 'Lobster';font-weight: 400;margin: 10px 0;">
        {{ question.title }}</h3>
</div>

<div style="box-sizing: inherit;font-family: 'Lobster';box-shadow: 0 4px 10px 0 rgba(0,0,0,0.2),0 4px 20px 0 rgba(0,0,0,0.19);transition: 0.5s;opacity: 0.7;border-left: 6px solid #ccc!important;margin: 16px!important;padding: 8px 16px!important;background-color: rgb(239, 229, 217)!important;color: black!important;border-color: rgb(139, 150, 32)!important;">

    <p style="box-sizing: inherit;">
        {{ question.text }}
    </p>

    <br/>

    {{ question.author }}

    <br/>
    <br/>
    <hr>
    <p style="box-sizing: inherit; font-style: italic;">
        {% trans "Your wedding page." %}
    </p>
</div>

</body>
</html>

web/templates/web/question_answer.html
{% extends 'web/base.html' %}
{% load i18n %}

{% block content %}
<div class="w3-margin w3-padding w3-card-4 w-green w-text-gray w-opacity">
    <h2>{% trans "Answer" %}</h2>
</div>


<div class="w3-left-align w3-padding w3-card-4 w3-leftbar w3-container w3-margin w-border-green w-gray w-opacity">
    {% if user.is_authenticated %}
    <div class="w3-right-align w3-large">
        <a href="{% url 'web:question-list' %}{{ question.id }}/"><i
                class="fa fa-bars w-hover-opacity w-text-green"></i></a>

        <span class="delimiter">&#124;</span>

        <a href="{% url 'web:question-list' %}{{ question.id }}/delete/"><i
                class="fa fa-close w-hover-opacity w-text-green"></i></a>
    </div>
    {% endif %}
    <h2>{{ question.title }}</h2>
    <p>{{ question.text|linebreaksbr }}</p>
    <div class="w3-right-align">
        <i class="fa fa-user-o"></i> {{ question.author|linebreaksbr }}&nbsp;&nbsp;&nbsp;
        <i class="fa fa-calendar"></i> {{ question.date.date }}&nbsp;&nbsp;&nbsp;
        <i class="fa fa-clock-o"></i> {{ question.date.time }}
    </div>
</div>


{% if user.is_authenticated %}
<form method="POST" class="w3-card-4 w3-margin w3-padding w3-leftbar w-margin-left w-form w-opacity w-gray w-text-green w-border-green" enctype="multipart/form-data">
    {% csrf_token %}

    {% for field in form %}
            <label class="">{{field.label_tag}}</label>
            <div class="">{{ field }}</div>
            <div class="">{{ field.errors }}</div>
    {% endfor %}


    <button type="submit" class="w-button w-hover-opacity w-text-green w-border-green w-gray">Uložit</button>

</form>

{% else %}
<div class="w3-card-4 w3-margin w3-padding w3-leftbar w-opacity w-gray w-text-black w-border-green w-opacity">
{% trans "You are not allowed to answer questions." %}
</div>
{% endif %}



{% endblock %}

web/templates/web/question_form.html
{% extends 'web/base.html' %}
{% load i18n %}

{% block content %}
    <div class="w3-card-4 w3-margin w3-padding w-opacity w-green w-text-gray">
        <h2>{% trans "New question" %}</h2>
    </div>

    <form method="POST" class="w3-card-4 w3-margin w3-padding w3-leftbar w-form w-opacity w-gray w-text-green w-border-green">{% csrf_token %}
        {% for field in form %}
            <label class="">{{field.label_tag}}</label>
            <div class="">{{ field }}</div>
            <div class="">{{ field.errors }}</div>
        {% endfor %}

        <button type="submit" class="w-button w-hover-opacity w-text-green w-border-green w-gray">{% trans "Save" %}</button>
    </form>
{% endblock %}

web/templates/web/question_list.html
{% extends 'web/base.html' %}
{% load i18n %}

{% block content %}

<div class="w3-card-4 w3-margin w3-padding w-opacity w-green w-text-gray">
    <h2>{% trans "Questions and maybe also answers" %}
        <span class="delimiter">&#124;</span>
        <a href="{% url 'web:question-create' %}#content">
            <div class="w-button w-hover-opacity w-text-gray w-border-gray">{% trans "Add question" %}</div>
        </a>
    </h2>
</div>

{% for q in  all_questions %}
<div id="question{{ q.id }}" class="w3-left-align w3-padding w3-card-4 w3-leftbar w3-container w3-margin w-border-green w-gray w-opacity">
    {% if user.is_authenticated %}
    <div class="w3-right-align w3-large">
        <a href="{% url 'web:question-list' %}{{ q.id }}/"><i
                class="fa fa-bars w-hover-opacity w-text-green"></i></a>

        <span class="delimiter">&#124;</span>

        <a href="{% url 'web:question-list' %}{{ q.id }}/delete/"><i
                class="fa fa-close w-hover-opacity w-text-green"></i></a>
    </div>
    {% endif %}
    <h2>{{ q.title }}</h2>
    <p>{{ q.text|linebreaksbr }}</p>
    <div class="w3-right-align">
        <i class="fa fa-user-o"></i> {{ q.author|linebreaksbr }}&nbsp;&nbsp;&nbsp;
        <i class="fa fa-calendar"></i> {{ q.date.date }}&nbsp;&nbsp;&nbsp;
        <i class="fa fa-clock-o"></i> {{ q.date.time }}
    </div>
</div>


<div class="w3-card-4 w3-padding w3-leftbar w3-container w3-margin w3-left-align w-border-green w-gray w-opacity w-margin-left">
    {% if q.answer %}
    {% if user.is_authenticated %}
    <div class="w3-right-align w3-large">
        <a href="/answer/{{ q.answer.id }}/"><i
                class="fa fa-bars w-hover-opacity w-text-green"></i></a>

        <span class="delimiter">&#124;</span>

        <a href="/answer/{{ q.answer.id }}/delete/"><i
                class="fa fa-close w-hover-opacity w-text-green"></i></a>
    </div>
    {% endif %}
    <p>{{ q.answer.text|linebreaksbr }}</p>
    <div class="w3-right-align">
        <i class="fa fa-user-o"></i> {{ q.answer.author|linebreaksbr }}&nbsp;&nbsp;&nbsp;
        <i class="fa fa-calendar"></i> {{q.answer.date.date}}&nbsp;&nbsp;&nbsp;
        <i class="fa fa-clock-o"></i> {{ q.answer.date.time }}
    </div>
    {% else %}
    <span>{% trans "Not answered yet." %}</span>
    {% if user.is_authenticated %}
    <a href="{% url 'web:question-list' %}{{ q.id }}/add-answer/"><span class="btnanswer">{% trans "Answer" %}</span></a>
    {% endif %}
    {% endif %}
</div>

{% endfor %}

{% endblock content %}

web/templates/web/question_private_form.html
{% extends 'web/base.html' %}

{% block content %}
<div class="w3-card-4 w3-margin w3-padding w-opacity w-green w-text-gray">
    <h2>Dotaz</h2>
</div>

{% if user.is_authenticated %}
<form method="POST" class="w3-card-4 w3-margin w3-padding w3-leftbar w-form w-opacity w-gray w-text-green w-border-green">
    {% csrf_token %}

    {% for field in form %}
    <label class="">{{field.label_tag}}</label>
    <div class="">{{ field }}</div>
    <div class="">{{ field.errors }}</div>
    {% endfor %}

    <button type="submit" class="w-button w-hover-opacity w-text-green w-border-green w-gray">Potvrdit</button>
</form>

{% else %}
Nemáte právo editovat dotazy.
{% endif %}

{% endblock %}

web/templates/web/registration_confirm_delete.html
{% extends 'web/base.html' %}
{% load i18n %}

{% block content %}
<div class="w3-margin w3-padding w3-card-4 w-green w-text-gray w-opacity">
    <h2>{% trans "Delete registration" %}</h2>
</div>
{% if user.is_authenticated %}
<form method="POST" class="w3-card-4 w3-margin w3-padding w3-leftbar w-form w-opacity w-gray w-text-green w-border-green" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="w-text-black">
      <h2>{{ object.name }} ({{ object.people_count }})</h2>
    </div>
    {% for field in form %}
    <label class="form label">{{field.label_tag}}</label>
    <div class="form text-area">{{ field }}</div>
    <div class="">{{ field.errors }}</div>
    {% endfor %}

    <button type="submit" class="w-button w-hover-opacity w-text-green w-border-green w-gray">{% trans "Confirm" %}</button>

</form>

{% else %}
<div class="w3-card-4 w3-margin w3-padding w3-leftbar w-opacity w-gray w-text-black w-border-green w-opacity">
{% trans "You are not allowed to delete registration." %}
</div>
{% endif %}

{% endblock %}

web/templates/web/registration_form.html
{% extends 'web/base.html' %}
{% load i18n %}

{% block content %}
    <div class="w3-card-4 w3-margin w3-padding w-opacity w-green w-text-gray">
        <h2>{% trans "Registration" %}</h2>
    </div>

    <form method="POST" class="w3-card-4 w3-margin w3-padding w3-leftbar w-form w-opacity w-gray w-text-green w-border-green">{% csrf_token %}
        {% for field in form %}
            <label class="">{{field.label_tag}}</label>
            <div class="">{{ field }}</div>
            <div class="">{{ field.errors }}</div>
        {% endfor %}

        <button type="submit" class="w-button w-hover-opacity w-text-green w-border-green w-gray">{% trans "Save" %}</button>
    </form>
{% endblock %}

web/templates/web/thanks.html
{% extends 'web/base.html' %}
{% load i18n %}

{% block content %}

<div class="w3-card-4 w3-padding w3-margin w-opacity w-green w-text-gray">
    <h2>{% trans "Thanks for registration" %}</h2>
</div>

{% endblock content %}